# Generated by Django 4.1.5 on 2023-01-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PF', '0003_rename_project_name_project_project_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='projects',
        ),
    ]
