# Generated by Django 4.1.5 on 2023-01-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PF', '0008_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
